# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20181220_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u0443\u0432\u0430\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='\u041f\u043e\u043a\u0430\u0437\u0443\u0432\u0430\u0442\u0438'),
        ),
    ]
