# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '\u041a\u043d\u0438\u0433\u0443', 'verbose_name_plural': '\u041a\u043d\u0438\u0433\u0438'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': '\u041c\u043e\u0432\u0443', 'verbose_name_plural': '\u041c\u043e\u0432\u0438'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='\u041e\u043f\u0438\u0441:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0456\u043a\u0430\u0446\u0456\u0457:'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
