# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181217_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440:'),
        ),
    ]
