# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 10:10
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441:'),
        ),
    ]
